name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # This enables manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get version from version.txt
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Set Docker tags
      run: |
        echo "DOCKER_TAGS=godver3/cli_battery:main,godver3/cli_battery:main-${{ env.VERSION }}" >> $GITHUB_ENV
        echo "DOCKER_TAGS_ARM64=godver3/cli_battery:main-arm64,godver3/cli_battery:main-${{ env.VERSION }}-arm64" >> $GITHUB_ENV

    - name: Build and push amd64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.DOCKER_TAGS }}
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

    - name: Build and push arm64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: true
        tags: ${{ env.DOCKER_TAGS_ARM64 }}
        build-args: |
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')